FROM openjdk:17

EXPOSE 8081

ADD TransformService/target/TransformService-0.0.1-SNAPSHOT.jar TransformService-0.0.1-SNAPSHOT.jar

WORKDIR /csvfiles

ADD csvfiles/profiles.csv profiles.csv
ADD csvfiles/meterReadings.csv meterReadings.csv

ENTRYPOINT [ "java", "-Dspring.profiles.active=prod", "-jar", "/TransformService-0.0.1-SNAPSHOT.jar" ]